### ISSUE TITLE
local variable epoch_logs is not assigned

### ISSUE THREAD

**Issue by AhmedAAkl** [experiencor/basic-yolo-keras#56]
Hi @experiencor  ,
i always have the same error appeared every time and i can't solve it
the error is 
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

how to solve it.

**Comment by experiencor** [comment]
Can you give the full error log? Which file gives rise to this error?

**Comment by AhmedAAkl** [comment]
this is the full exception traceback, but after search i think that my error is in the input. is it right?
Traceback (most recent call last):
  File "C:\Users\A.Akl\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\A.Akl\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\engine\training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
TypeError: 'BatchGenerator' object is not an iterator

Traceback (most recent call last):
  File "<ipython-input-23-c8cab4d9ac63>", line 1, in <module>
    runfile('K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master/train.py', wdir='K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master')
  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master/train.py", line 137, in <module>
  debug              = config['train']['debug'])
  File "K:\dream soft\projects\basic-yolo-keras\basic-yolo-keras-master\frontend.py", line 445, in train
    max_q_size   = 8)
  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\engine\training.py", line 1913, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

**Comment by experiencor** [comment]
Yes. You can check whether train_images and valid_images in train.py are empty.

**Comment by AhmedAAkl** [comment]
another explanation:
In dataset preparation, how to convert bounding boxes with objects index to .xml files

**Comment by experiencor** [comment]
@AhmedAAkl Have you solved this problem by checking the input?

**Comment by AhmedAAkl** [comment]
@experiencor , sorry for late reply.
but i was very busy. the problem was in the url of the images in  .xml files, so when is repair it the code run and skipped this error.

My problem now is that 
ValueError: validation_data should be a tuple `(val_x, val_y, val_sample_weight)` or `(val_x, val_y)`. Found: <preprocessing.BatchGenerator object at 0x000000E117B3B8D0>
this error,  occurred when i try to run code

**Comment by experiencor** [comment]
@AhmedAAkl Could you provide the full log?

**Comment by AhmedAAkl** [comment]
Traceback (most recent call last):

  File "<ipython-input-1-c8cab4d9ac63>", line 1, in <module>
    runfile('K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master/train.py', wdir='K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master')

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master/train.py", line 143, in <module>
    debug              = config['train']['debug'])

  File "K:\dream soft\projects\basic-yolo-keras\basic-yolo-keras-master\frontend.py", line 451, in train
    max_q_size   = 8)

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\engine\training.py", line 1822, in fit_generator
    str(validation_data))

ValueError: validation_data should be a tuple `(val_x, val_y, val_sample_weight)` or `(val_x, val_y)`. Found: <preprocessing.BatchGenerator object at 0x000000858083D080>

**Comment by experiencor** [comment]
Sounds like something is wrong with the validation generator. I would suggest you use the provided notebook (Yolo Step-by-Step.ipynb) to explore your dataset first. The notebook walks through the whole process and is very helpful in debugging.

**Comment by AhmedAAkl** [comment]
@experiencor  thanx, i will try it.
but, when i check the valid_batch variable in frontend.py file i found that it divided the data set
but the problem as appeared in the error description is the validation_data variable should be a tuple.

**Comment by AhmedAAkl** [comment]
@experiencor 
i walked step by step in the .ipynb file but, i faced the same error in the same line
i think i have problem with my dataset
the structure is as follow:
-dataset
          -train
                  -stopimages
                   -stopannots
         -validate
                      -stopimages
                       -stopannots

annotations is in .xml file as mentioned.
where is the problem?

**Comment by experiencor** [comment]
For ```'./dataset1/train/stop/369.jpg```, should it be ```'./dataset/train/stop/369.jpg```? Note the trailing number 1 after dataset.

**Comment by AhmedAAkl** [comment]
@experiencor , yes i take care of it in my config.json file 
i tried to run the code in the raccoon dataset instead to make sure that there is something wrong with my dataset 
but i got another error.
Traceback (most recent call last):

  File "<ipython-input-13-c8cab4d9ac63>", line 1, in <module>
    runfile('K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master/train.py', wdir='K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master')

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "K:/dream soft/projects/basic-yolo-keras/basic-yolo-keras-master/train.py", line 146, in <module>
    debug              = config['train']['debug'])

  File "K:\dream soft\projects\basic-yolo-keras\basic-yolo-keras-master\frontend.py", line 451, in train
    max_q_size   = 8)

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\A.Akl\Anaconda3\lib\site-packages\keras\engine\training.py", line 1817, in fit_generator
    val_x, val_y, val_sample_weight = validation_data

ValueError: too many values to unpack (expected 3)

i think i have something error in my code or there is an error in the batchGenerator class

**Comment by AhmedAAkl** [comment]
in dataset sturcture.
is there another thing to add to train the model
this is my config.json file 
{
    "model" : {
        "architecture":         "Tiny Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["kangaroo"]
    },

    "train": {
        "train_image_folder":   "./dataset/images/",
        "train_annot_folder":   "./dataset/annots/",                
        "train_times":          10,           
        "batch_size":           16,             
        "learning_rate":        1e-4,           
        "nb_epoch":             50,             
        "warmup_batches":       100,            
        "object_scale":         5.0 ,           
        "no_object_scale":      1.0,            
        "coord_scale":          1.0,            
        "class_scale":          1.0,            
        "saved_weights_name":   "stop_sign.h5",
        "debug":                true            
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}

**Comment by AhmedAAkl** [comment]
@experiencor  the one thing that i have changed in your code is the import statement 
in the preprocessing.py file from
from keras.utils import Sequence
to
from keras.utils.data_utils import Sequence
because there is an error to import the first one 
ImportError: cannot import name 'Sequence'
so i searched and found that the Sequence class transferred in another package.

to know BatchGenerator that rises the error inherits the Sequence Class
is this right?

**Comment by experiencor** [comment]
In your config file, ```"labels": ["kangaroo"]```? Should it be ```stop``` - the name of the label?

**Comment by AhmedAAkl** [comment]
@experiencor . yes you are right. but i changed it with the dataset for kangaroo to know where is the error.
kindly, look for the previous comment.

**Comment by experiencor** [comment]
What Keras version do you use?

**Comment by AhmedAAkl** [comment]
version 2.0.1 through anaconda

**Comment by experiencor** [comment]
May you try the latest Keras? I use 2.0.8 but 2.011 is also fine.

**Comment by AhmedAAkl** [comment]
could you tell me the structure of the dataset?

**Comment by AhmedAAkl** [comment]
when i updated keras version to 2.1.1 it runs i will in kangaroo dataset i will go with it.
thanks alot
